### ISSUE TITLE
non ASCII characters in column name

### ISSUE THREAD

**Issue by julienbalas** [wsdookadr/fieldtop#6]
Hi
I've an issue with fieldtop : it doesn't display very much.

user@host:~$ curl http://localhost/fieldtop/fieldtop.php
vOAutresAdh�rent
user@host:~$ 

The column displayed contains mostly null value (18Knull and 3 non null value)
The execution of "fieldtop.sql" in a mysql console give me 4001 rows of results.
If I rename my column to avoid the é character it seems to work but it takes hours to run.
My database has 4001 columns and 70Go to check, so i understand that it can not be lightning fast, but still....

**Comment by wsdookadr** [comment]
Hi Julien,

The output you provided is surprising. The table header is not
present.  Moreover, since you're calling it from a web server (and not
from CLI), one would expect HTML markup to be present in the output
(if I'm not mistaken, this is how the code currently works).

About your use-case with 4001 columns, it may certainly be the case that
some situations require such a large number of columns.

I've done some reading and discussed this topic with a few people that
are more knowledgeable than me on this topic.

I think the main reason why it's taking hours is that you have a large
number of columns and some of the columns (you can elaborate more on
this) are probably not equipped with indexes, and as a result,
[full-table](http://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_full_table_scan) [scans](http://dev.mysql.com/doc/refman/5.7/en/how-to-avoid-table-scan.html) are being performed.

Here are two possible approaches:
- placing indexes on numeric columns [2] and expression 
  indexes [1] on the length function for the string/text
  columns
- creating a table that would always hold max/min for 
  all columns. placing triggers on all columns in all 
  tables to update the previously mentioned table

For both of these approaches, the entire logic could be placed in
fieldtop, and the triggers/indexes (depending on which you choose to
use) can be created only if they're not already present (I suppose
they can be named in a certain way, so that it's easy to identify that
they were created by fieldtop).

However, it would be necessary to keep in sync with column changes
(e.g. if a column is added, a new index needs to be created with the
1st approach or, in the 2nd approach, a new trigger would need to be
created). Both situations will add overhead. How much overhead, and to
what extent one would be better than the other should probably be the
subject of a benchmark.

A different approach is conceivable, one that would leverage existing
clues related to the way MySQL operates internally. The description of
this approach is underdeveloped since my knowledge about it is limited
(I imagine it would require a lot of study/reading/research on the
MySQL documentation and probably the codebase too). The assumption
with this approach is that there are clues, or even direct information
on the max/min values, and this information is pre-computed and stored
in various places. This might be metadata, residual or forensic data.

There may be other ways of doing this, which is why, you may elaborate on
a different way of doing this. We welcome (and encourage) pull requests.

[1] About expression indexes. In MySQL, they're [not available](http://stackoverflow.com/a/10595073/827519) and it seems
    like the closest one can get to those are [generated columns](http://mysqlserverteam.com/generated-columns-in-mysql-5-7-5/).
[2] For AUTO_INCREMENT numeric columns, there may be a [fast way](http://dba.stackexchange.com/a/104549/21057) to get the
    maximum value using the information_schema.

**Comment by julienbalas** [comment]
Hi,
yes, i'm ok with the time needed to process all the data, as you said not every columns has an index so it seems normal to be CPU intensive.

About the non ASCII column name : there is no HTML output, which is indeed surprising (hence the issue ;) ) 
it seems that it output an error, an exception or something.

If i find the time to look at the code i'll try to provide
one PR for non ASCII handling, 
and one to be able to configure the hostname (localhost is hardcoded)

Best regards
